main/urls.py
from django.urls import path
from main.views import show_main,show_xml,show_xml_by_id,show_json,show_json_by_id,\
            register, login_user, logout_user,add_amount,sub_amount,delete_amount,\
            get_items_json,add_items_ajax, get_all_amount, delete_items_ajax, add_item,create_item_flutter_new,show_json_user

app_name = "main"

urlpatterns = [
    path("", show_main, name = "show_main"),
    path("add-item/",add_item, name="add_item"),
    path("xml/",show_xml, name="show_xml"),
    path("xml/<int:id>/",show_xml_by_id, name="show_xml_by_id"),
    path("json/",show_json, name="show_json"),
    path("json/<int:id>/",show_json_by_id, name="show_json_by_id"),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    
    path("add-amount/<int:id>/",add_amount, name='add_amount'),
    path("sub-amount/<int:id>/",sub_amount, name='sub_amount'),
    path("delete-amount/<int:id>/",delete_amount, name='delete_amount'),
    # path('edit-product/<int:id>', edit_product, name='edit_product'),

    path('get-items/', get_items_json, name='get_items_json'),
    path('create-ajax/', add_items_ajax, name='add_items_ajax'),
    path('get-all-amount/',get_all_amount,name='get_all_amount'),
    path("delete-item-ajax/<int:id>/",delete_items_ajax, name='delete_item_ajax'),
    path('create-flutter/', create_item_flutter_new, name='create_item_flutter'),

    path("json-item/<str:uname>/",show_json_user, name="show_json_user"),
]

olshop_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('auth/', include('authentication.urls')),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    amount = models.IntegerField()
    description = models.TextField()


    def __str__(self) -> str:
        return self.name

main/forms.py
from django.forms import ModelForm
from main.models import Item
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ["name", "amount", "description"]

    def __init__(self, *args, **kwargs): 
        super().__init__(*args, **kwargs) 
        self.fields['name'].widget.attrs.update({ 
            'class': 'form-control', 
            'name':'name', 
            'id':'name', 
            'type':'text', 
            'placeholder':'Nama Barang', 
            })
        
        self.fields['amount'].widget.attrs.update({ 
            'class': 'form-control', 
            'name':'amount', 
            'id':'amount', 
            'type':'number', 
            'placeholder':'Jumlah Barang', 
            'min':'0',
            })
        self.fields['description'].widget.attrs.update({ 
            'class': 'form-control', 
            'name':'description', 
            'id':'description', 
            'type':'text-area', 
            'placeholder':'Deskripsi Barang', 
            })   

class RegisterForm(UserCreationForm):
    class Meta: 
        model = User 
        fields = ('username', 'password1', 'password2') 

    def __init__(self, *args, **kwargs): 
        super().__init__(*args, **kwargs) 
        self.fields['username'].widget.attrs.update({ 
            'class': 'input-field', 
            'required':'', 
            'name':'username', 
            'id':'username', 
            'type':'text', 
            'placeholder':'Username', 
            'maxlength': '16', 
            'minlength': '6', 
            }) 
        self.fields['password1'].widget.attrs.update({ 
            'class': 'input-field', 
            'required':'', 
            'name':'password1', 
            'id':'password1', 
            'type':'password', 
            'placeholder':'Password', 
            'maxlength':'22',  
            'minlength':'8' 
            }) 
        self.fields['password2'].widget.attrs.update({ 
            'class': 'input-field', 
            'required':'', 
            'name':'password2', 
            'id':'password2', 
            'type':'password', 
            'placeholder':'Validate password', 
            'maxlength':'22',  
            'minlength':'8' 
            }) 

main/views.py
import json
from django.shortcuts import render, redirect
from django.db.models import Sum
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound, JsonResponse
from django.core import serializers
from main.models import Item
from main.forms import  RegisterForm, ItemForm
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

import datetime


@csrf_exempt
def create_item_flutter_new(request):
    if request.method == 'POST':
        # print("TEST 1")
        data = json.loads(request.body)

        new_item = Item.objects.create(
            user = request.user,
            name = data["name"],
            amount = int(data["amount"]),
            description = data["description"],
        )
        print(request.user, "ASAS")
        # print("TEST 2")
        new_item.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

# @login_required(login_url='/login')
@csrf_exempt
def show_json_user(request,uname):
    # print(uname)
    data_item = Item.objects.all()
    for data in data_item:
        if data.user.username == uname:
            user_id = data.user
            data = Item.objects.filter(user = user_id)
            break
        else:
            data = []
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

# Create your views here.
@login_required(login_url='/login')
def show_main (request):
    jumlah_item = Item.objects.filter(user = request.user).count()
    if(jumlah_item != 0):
        items = Item.objects.filter(user = request.user)[:jumlah_item-1]
    else:
        items = Item.objects.filter(user = request.user)
    
    item_akhir = Item.objects.filter(user = request.user).last()
    jumlah_barang = Item.objects.filter(user = request.user).aggregate(total = Sum("amount"))['total']

    if jumlah_barang == None:
        jumlah_barang = 0

    context = {
        "Kata_Awal" : "Ayo Beli Yuk!",
        "Nama" : request.user.username,
        "Kelas" : "PBP - D",
        "items"  : items,
        "item_akhir": item_akhir,
        "jumlah_jenis" : jumlah_item,
        "jumlah_barang" : jumlah_barang,
        'last_login': request.COOKIES['last_login'],
    }
    return render(request,"homepage.html",context)

def register(request):
    form = RegisterForm()

    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def get_items_json(request):
    items = Item.objects.filter(user = request.user)
    if(items != None):
        return HttpResponse(serializers.serialize('json', items))
    return HttpResponse(0)

def get_all_amount(request):
    jumlah_barang = Item.objects.filter(user = request.user).aggregate(total = Sum("amount"))['total']
    return HttpResponse(jumlah_barang)

@csrf_exempt
def add_items_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        user = request.user

        new_item = Item(name=name, amount=amount, description=description, user=user)
        new_item.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

def add_amount(request,id):
    jumlah = Item.objects.get(pk =id)
    jumlah.amount+=1
    jumlah.save()
    return HttpResponseRedirect(reverse('main:show_main'))

def sub_amount(request,id):
    jumlah = Item.objects.get(pk=id)
    jumlah.amount-=1
    if jumlah.amount == 0:
        jumlah.delete()
        return HttpResponseRedirect(reverse('main:show_main'))
    jumlah.save()
    return HttpResponseRedirect(reverse('main:show_main'))

def delete_amount(request,id):
    jumlah = Item.objects.get(pk=id)
    jumlah.delete()
    return HttpResponseRedirect(reverse('main:show_main'))

@csrf_exempt
def delete_items_ajax(request,id):
    if request.method == 'DELETE':
        jumlah = Item.objects.get(pk=id)
        jumlah.delete()
        return HttpResponse(b"DELETE", status=201)
    
    return HttpResponseNotFound()

# def edit_product(request, id):
#     # Get product berdasarkan ID
#     product = Item.objects.get(pk = id)

#     # Set product sebagai instance dari form
#     form = ItemForm(request.POST or None, instance=product)

#     if form.is_valid() and request.method == "POST":
#         # Simpan form dan kembali ke halaman awal
#         form.save()
#         return HttpResponseRedirect(reverse('main:show_main'))

#     context = {'form': form,
#                "Nama" : request.user.username,
#                 "heading": "Edit Item!",
#                 "value_button":"Edit Item",
#                 "Kelas" : "PBP - D",}
#     return render(request, "edit_product.html", context)
    

@login_required(login_url='/login')
def add_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        item = form.save(commit=False)
        item.user = request.user
        item.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = { 'form': form,
                "Nama" : request.user.username,
                "heading": "Add Item!",
                "value_button":"Add Item",
                "Kelas" : "PBP - D",}
    return render(request, "add_item.html", context)

@login_required(login_url='/login')
def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

# @login_required(login_url='/login')
def show_json(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@login_required(login_url='/login')
def show_xml_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

@login_required(login_url='/login')
def show_json_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

main/templates/add_item.html
{% extends 'base.html' %}
{% comment %} {% load static %} {% endcomment %}

{% block meta %}
    <title>Add Item</title>
    <link rel="stylesheet"
          href= "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        .input-icons i {
            position: start;
        }
         
        .input-icons {
            width: 100%;
            margin-bottom: 10px;
        }
         
    </style>
{% endblock meta %}

{% block navbar %}
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <!-- Container wrapper -->
    
    <div class="container-fluid">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fa fa-user fa-2x" style = "color:white;"></i>
        </a>

        <ul class="dropdown-menu dropdown-menu-" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">{{Nama}}</a></li>
            <li><a class="dropdown-item" href="#">{{Kelas}}</a></li>
        </ul>

        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
            <a class="nav-link" href="#"><h4>Qemul Shop</h4></a>
            </li>
        </ul>
    </div>
    <div class="d-flex align-items-center">
        <!-- Logout -->
        <a class="text-reset me-3" href="{% url 'main:logout' %}">
            <i class="fa fa-sign-out fa-2x" style="color:white;"></i>
        </a>
    </div>
</nav>
  <!-- Navbar -->
{% endblock navbar %}


{% block content %}  

<div center style = "margin-top:100px; text-align:center">
    <h1 class = "title text-center">{{heading}}</h1>  

    <form method="POST" actione="." style="max-width:450px;margin:auto" id="register-form"> 
        {% csrf_token %} 
        
            <div class="input-icons">
                {{form.name}} 
            </div>
            <div class="input-icons"> 
                {{form.amount}} 
            </div> 
            <div class="input-icons"> 
                {{form.description}} 
            </div> 

            <input type="submit" class="submit" value="{{value_button}}" style = "width:200px;"> 
    </form> 
</div>

{% endblock content %}

main/templates/edit_product.html
{% extends 'add_item.html' %}

main/templates/homepage.html
{% extends 'base.html' %}

{% block meta %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock meta %}
    
{% block navbar %}
<!-- Navbar -->
<nav class="navbar  navbar-expand-lg navbar-dark bg-dark">
    <!-- Container wrapper -->
    
    <div class="container-fluid">
        <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fa fa-user fa-2x" style = "color:white;"></i>
        </a>

        <ul class="dropdown-menu dropdown-menu-" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item">{{Nama}}</a></li>
            <li><a class="dropdown-item">{{Kelas}}</a></li>
        </ul>

        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
            <a class="nav-link"><h4>Qemul Shop</h4></a>
            </li>
        </ul>
    </div>
      <!-- Collapsible wrapper -->
  
      <!-- Add Item -->
    <div class="d-flex align-items-center">
        <!-- Icon -->
        <a class="text-reset me-3" data-bs-toggle="modal" data-bs-target="#exampleModal">
          <i class="fa fa-shopping-cart fa-2x" style = "color:white;"></i>
        </a>
        
        <!-- Logout -->
        <a class="text-reset me-3" href="{% url 'main:logout' %}">
            <i class="fa fa-sign-out fa-2x" style="color:white;"></i>
        </a>
    </div>
    <!-- Container wrapper -->
</nav>
  <!-- Navbar -->
{% endblock navbar %}

{% block content %}
<div class = "container py-5">
    <h3 class="text-center" id = judul></h3>
    {% comment %} <p>HALLo
        
        {% for i in items  %}
            {{i.user}} -
        {% endfor %}
            
    </p> {% endcomment %}
    <div class="row row-cols-1 row-cols-md-3 g-4 py-5" id = items_cards></div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="form" onsubmit="return false;">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name" class="col-form-label">Name:</label>
                        <input type="text" class="form-control" id="name" name="name">
                    </div>
                    <div class="mb-3">
                        <label for="amount" class="col-form-label">Amount:</label>
                        <input type="number" class="form-control" id="amount" name="amount">
                    </div>
                    <div class="mb-3">
                        <label for="description" class="col-form-label">Description:</label>
                        <textarea class="form-control" id="description" name="description"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Item</button>
            </div>
        </div>
    </div>
</div>

<footer style = "bottom: 0%; position: fixed;">
    <p style ="height:10px">Sesi terakhir login: {{ last_login }}</p>
</footer>

<script>
    async function getItems() {
        return fetch("{% url 'main:get_items_json' %}").then((res) => res.json())
    }
    async function getAllAmount() {
        return fetch("{% url 'main:get_all_amount' %}").then((res) => res.json())
    }

    async function refreshItems() {
        var jumlah_item,item_awal,item_akhir, all_amount
        document.getElementById("items_cards").innerHTML = ""
        // indexing item dari satu sampai last minus satu dan last
        const items = await getItems()
        // console.log(idItem)
        
        if(items != 0){
            jumlah_item = items.length
            item_awal = items.slice(0,jumlah_item-1)
            item_akhir = items[jumlah_item-1]

            console.log(items)
            console.log(item_awal)
            console.log(item_akhir)

            all_amount = await getAllAmount()
            document.getElementById("judul").style = "margin-top:0px"
            document.getElementById("judul").innerHTML = `Hore!! Kamu Memiliki ${jumlah_item} Item Dengan Total ${all_amount} Buah ?!`
        }else{
            document.getElementById("judul").style = "margin-top:150px"
            document.getElementById("judul").innerHTML = `Sayang Sekali Kamu Belum Ada Penambahan Item Nih!`
            return
        } 
        
        let htmlString = ``
        item_awal.forEach((item) => {
            {% comment %} console.log(item.fields.user) {% endcomment %}
            htmlString += `\n
            <div class="col">
                <div class="card text-center">
                    <div class="card-header" style = "background-color:gray">
                        ${item.fields.name}
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">${item.fields.name}</h5>
                        <p class="card-text">${item.fields.description}</p>
                    </div>
                    <div class="text-center">
                        <h3>${item.fields.amount}</h3>
                    </div>
                    <div class="card-body" style = "background-color:gray">
                        <a href="add-amount/${item.pk}" class="btn btn-dark">+</a>
                        <a href = "sub-amount/${item.pk}" class ="btn btn-dark">-</a>
                        <a href = "edit-product/${item.pk}" class ="btn btn-dark">?</a>
                        <a class ="btn btn-dark" onclick="deleteItems(${item.pk})">x</a>
                    </div>
                </div>
            </div>` 
        })
        htmlString += `\n
            <div class="col">
                <div class="card text-center">
                    <div class="card-header" style = "background-color:black; color:white">
                        ${item_akhir.fields.name}
                    </div>
                    <div class="card-body">
                        <h5 class="card-title" style = "color:red">${item_akhir.fields.name}</h5>
                        <p class="card-text" style = "color:red">${item_akhir.fields.description}</p>
                    </div>
                    <div class="text-center" style = "color:red">
                        <h3>${item_akhir.fields.amount}</h3>
                    </div>
                    <div class="card-body" style = "background-color:black">
                        <a href="add-amount/${item_akhir.pk}" class="btn btn-secondary">+</a>
                        <a href = "sub-amount/${item_akhir.pk}" class ="btn btn-secondary">-</a>
                        <a href = "edit-product/${item_akhir.pk}" class ="btn btn-secondary">?</a>
                        <a class ="btn btn-secondary" onclick="deleteItems(${item_akhir.pk})">x</a>
                    </div>
                </div>
            </div>`

        document.getElementById("items_cards").innerHTML = htmlString
    }
    refreshItems()

    function addItems() {
        fetch(`/create-ajax/`, {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshItems)

        document.getElementById("form").reset()
        return false
    }

    function deleteItems(idItem) {
        fetch(`/delete-item-ajax/${idItem}/`, {
            method: "DELETE",
        }).then(refreshItems())

        return false
    }

    document.getElementById("button_add").onclick = addItems
</script>
{% endblock content %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}
{% comment %} <section class="vh-100"> {% endcomment %}
<div class="tab-content" style="margin-top: 100px;">
    <div class = "form-control">
        <h1 style="text-align: center; margin-top: 30px;">Login To QemulShop</h1>
        
        <div class= "tab-pane fade show active" style="justify-content: center; display: flex; margin-top: 30px;">
            <form method="POST" action="">
                {% csrf_token %}
                <table>
                    <tr>
                        <td>Username: </td>
                        <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                    </tr>
                            
                    <tr>
                        <td>Password: </td>
                        <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                    </tr>
                </table>

                <div class="d-flex align-items-center justify-content-center pb-4" style="margin-top: 10px;"> 
                    <input class="btn btn-primary" type="submit" value="Login" style="width: 250px;">
                </div>
            </form>
        </div>
           
        <div class="d-flex align-items-center justify-content-center pb-4" style="margin-top:5px">
            {% if messages %}
                <ul>
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}     
        </div>

        <div class="d-flex align-items-center justify-content-center pb-4">
            Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a>
        </div>
    </div>
    
</div>
<footer style = "bottom: 0%; position: fixed; background-color:gray;">
    <p style ="color:white; height:10px">Copyright ©QEMUL.INC. All rights reserved.</p>
</footer>
{% comment %} </section> {% endcomment %}

{% endblock content %} 

main/templates/register.html
{% extends 'base.html' %}
{% comment %} {% load static %} {% endcomment %}

{% block meta %}
    <title>Register</title>
    <link rel="stylesheet"
          href= "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        .input-icons i {
            position: absolute;
        }
         
        .input-icons {
            width: 100%;
            margin-bottom: 10px;
        }
         
        .icon {
            padding: 10px;
            color: black;
            min-width: 50px;
            text-align: center;
        }
         
        .input-field {
            width: 100%;
            padding: 10px;
            text-align: center;
        }
         
        h2 {
            color: green;
        }
    </style>
{% endblock meta %}

{% block content %}  

<div center style = "margin-top:120px; text-align:center">
    <h1 class = "title text-center">Register</h1>  

    <form method="POST" actione="." style="max-width:450px;margin:auto" id="register-form"> 
        {% csrf_token %} 
        
            <div class="input-icons">
                <i class="fa fa-user icon fa-2x"></i>
                {{form.username}} 
            </div>
            <div class="input-icons"> 
                <i class="fa fa-key icon fa-2x"></i>
                {{form.password1}} 
            </div> 
            <div class="input-icons"> 
                <i class="fa fa-key icon fa-2x" style = "color:gray"></i>
                {{form.password2}} 
            </div> 

            <input type="submit" class="submit" value="Register" style = "width:130px;"> 
    </form> 

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}
</div>

{% endblock content %}